/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2025-05-04 06:48:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginSignup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>CampusConnect Auth</title>\r\n");
      out.write("<link rel = \"stylesheet\" href=\"CSS/loginSignup_style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\" id=\"container\">\r\n");
      out.write("	<!-- Sign Up Form -->\r\n");
      out.write("	<div class=\"form-container sign-up-container\">\r\n");
      out.write("		<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/signup\" method=\"POST\" onsubmit=\"return validateSignUp()\">\r\n");
      out.write("			<h1>Create Account</h1>\r\n");
      out.write("			<select name=\"role\" required>\r\n");
      out.write("				<option value=\"\">Select Role</option>\r\n");
      out.write("				<option value=\"user\">User</option>\r\n");
      out.write("				<option value=\"admin\">Admin</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			<input type=\"text\" name=\"name\" placeholder=\"Name\" required>\r\n");
      out.write("			<input type=\"text\" name=\"rollNumber\" placeholder=\"Roll Number\" required>\r\n");
      out.write("			<select name=\"branch\" required>\r\n");
      out.write("				<option value=\"\">Select Branch</option>\r\n");
      out.write("				<option value=\"cse-aiml\">CSE-AIML</option>\r\n");
      out.write("				<option value=\"cse\">CSE</option>\r\n");
      out.write("				<option value=\"ece\">ECE</option>\r\n");
      out.write("				<option value=\"eee\">EEE</option>\r\n");
      out.write("				<option value=\"it\">IT</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			<input type=\"email\" name=\"email\" placeholder=\"Email\" required id=\"signUpEmail\">\r\n");
      out.write("			<input type=\"password\" name=\"password\" placeholder=\"Password\" required id=\"signUpPassword\">\r\n");
      out.write("			<button>Sign Up</button>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Sign In Form -->\r\n");
      out.write("	<div class=\"form-container sign-in-container\">\r\n");
      out.write("		<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" method=\"POST\" onsubmit=\"return validateLogIn()\">\r\n");
      out.write("			<h1>Sign In</h1>\r\n");
      out.write("			<select name=\"role\" required>\r\n");
      out.write("				<option value=\"\">Select Role</option>\r\n");
      out.write("				<option value=\"user\">User</option>\r\n");
      out.write("				<option value=\"admin\">Admin</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			<input type=\"email\" name=\"email\" placeholder=\"Email\" required id=\"signInEmail\">\r\n");
      out.write("			<input type=\"password\" name=\"password\" placeholder=\"Password\" required id=\"signInPassword\">\r\n");
      out.write("			<a href=\"#\">Forgot your password?</a>\r\n");
      out.write("			<button>Sign In</button>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Overlay -->\r\n");
      out.write("	<div class=\"overlay-container\">\r\n");
      out.write("		<div class=\"overlay\">\r\n");
      out.write("			<div class=\"overlay-panel overlay-left\">\r\n");
      out.write("				<h1>Welcome Back!</h1>\r\n");
      out.write("				<p>To keep connected with us please login with your personal info</p>\r\n");
      out.write("				<button class=\"ghost\" id=\"signIn\">Sign In</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"overlay-panel overlay-right\">\r\n");
      out.write("				<h1>Hello, Friend!</h1>\r\n");
      out.write("				<p>Enter your details and start your journey with us</p>\r\n");
      out.write("				<button class=\"ghost\" id=\"signUp\">Sign Up</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- JS for Panel Switch -->\r\n");
      out.write("<script>\r\n");
      out.write("	document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("		const signUpButton = document.getElementById('signUp');\r\n");
      out.write("		const signInButton = document.getElementById('signIn');\r\n");
      out.write("		const container = document.getElementById('container');\r\n");
      out.write("\r\n");
      out.write("		signUpButton.addEventListener('click', function () {\r\n");
      out.write("			container.classList.add(\"right-panel-active\");\r\n");
      out.write("		});\r\n");
      out.write("		signInButton.addEventListener('click', function () {\r\n");
      out.write("			container.classList.remove(\"right-panel-active\");\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	// Validation for Sign Up form\r\n");
      out.write("	function validateSignUp() {\r\n");
      out.write("		const email = document.getElementById('signUpEmail').value;\r\n");
      out.write("		const password = document.getElementById('signUpPassword').value;\r\n");
      out.write("		const emailPattern = /^[a-zA-Z0-9._%+-]+@bvrithyderabad\\.edu\\.in$/;\r\n");
      out.write("		const passwordPattern = /^(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$/;\r\n");
      out.write("\r\n");
      out.write("		if (!emailPattern.test(email)) {\r\n");
      out.write("			alert(\"College Email must end in @bvrithyderabad.edu.in\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (!passwordPattern.test(password)) {\r\n");
      out.write("			alert(\"Password must be at least 8 characters long, include an uppercase letter, a number, and a special character.\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// Validation for log In form\r\n");
      out.write("	function validateLogIn() {\r\n");
      out.write("		const email = document.getElementById('signInEmail').value;\r\n");
      out.write("		const password = document.getElementById('signInPassword').value;\r\n");
      out.write("		const emailPattern = /^[a-zA-Z0-9._%+-]+@bvrithyderabad\\.edu\\.in$/;\r\n");
      out.write("		const passwordPattern = /^(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$/;\r\n");
      out.write("\r\n");
      out.write("		if (!emailPattern.test(email)) {\r\n");
      out.write("			alert(\"College Email must end in @bvrithyderabad.edu.in\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (!passwordPattern.test(password)) {\r\n");
      out.write("			alert(\"Password must be at least 8 characters long, include an uppercase letter, a number, and a special character.\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("	const urlParams = new URLSearchParams(window.location.search);\r\n");
      out.write("    if (urlParams.get(\"error\") === \"true\") {\r\n");
      out.write("        alert(\"Invalid credentials. Please try again.\");\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
