/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2025-05-04 06:11:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.campusconnect.model.User;

public final class viewExp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/includes/navigation.jsp", Long.valueOf(1746280004446L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("com.campusconnect.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>View Placement Experiences</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/viewExp_style.css\">\r\n");
      out.write("  	<link rel=\"stylesheet\" href=\"CSS/navigation_style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");

    User user = (User) session.getAttribute("user");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"nav-bar\">\r\n");
      out.write("    <div id=\"logo-section\">\r\n");
      out.write("        <a href=\"#\">CampusConnect</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"menu-icon\">\r\n");
      out.write("        <div class=\"bar\" id=\"bar1\"></div>\r\n");
      out.write("        <div class=\"bar\" id=\"bar2\"></div>\r\n");
      out.write("        <div class=\"bar\" id=\"bar3\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <ul class=\"nav-links\">\r\n");
      out.write("        <li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("        ");
 if (user != null) { 
      out.write(" <!-- if the user is logged in -->\r\n");
      out.write("        	<li><a href=\"#\">About</a></li>\r\n");
      out.write("            <li><a href=\"logout.jsp\">Logout</a></li>\r\n");
      out.write("            <li><a href=\"#\">Podcasts</a></li>\r\n");
      out.write("            <li><a href=\"interviewExp.jsp\">Interview Experinces</a></li>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <li><a href=\"loginSignup.jsp\">Signin/Login</a></li>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"addBtn\">\r\n");
      out.write("    <a href=\"submit.jsp\" class=\"add-button\">+ Add Experience</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    ");

        String[] companies = {"Infosys", "Amazon", "TCS", "Wipro", "Cognizant"};
        String[] salaries = {"4.5 LPA", "12 LPA", "3.6 LPA", "7.5 LPA", "6.2 LPA"};
        String[] names = {"Priya Sharma", "Ravi Teja", "Sneha Das", "John Doe", "Amit Kumar"};
        String[] rollNumbers = {"23wh5a6601", "23wh5a6602", "23wh5a6603", "23wh5a6604", "23wh5a6605"};
        String[] durations = {"1 month internship", "2 weeks online assessment", "10 days online + HR round", "3 months internship", "1 month project"};
        String[] questions = {
            "OOPs Concepts, Palindrome Program, Java Basics",
            "DSA problems, Behavioral questions, SQL queries",
            "Aptitude, Basic coding, Team project discussion",
            "System design, Problem-solving, Data Structures",
            "Coding test, Algorithms, Soft skills"
        };

    for (int i = 0; i < companies.length; i++) {

      out.write("\r\n");
      out.write("<div class=\"experience-card\">\r\n");
      out.write("    <h2>");
      out.print( companies[i] );
      out.write("</h2>\r\n");
      out.write("    <p><span class=\"label\">Name:</span> ");
      out.print( names[i] );
      out.write("</p>\r\n");
      out.write("    <p><span class=\"label\">Roll Number:</span> ");
      out.print( rollNumbers[i] );
      out.write("</p>\r\n");
      out.write("    <p><span class=\"label\">Salary:</span> ");
      out.print( salaries[i] );
      out.write("</p>\r\n");
      out.write("    <p><span class=\"label\">Duration:</span> ");
      out.print( durations[i] );
      out.write("</p>\r\n");
      out.write("    <p><span class=\"label\">Interview Questions:</span> ");
      out.print( questions[i] );
      out.write("</p>\r\n");
      out.write("</div>\r\n");

    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("  <script>\r\n");
      out.write("    let menu = document.querySelector(\"#menu-icon\");\r\n");
      out.write("    let navLinks = document.querySelector(\".nav-links\");\r\n");
      out.write("    menu.onclick = function () {\r\n");
      out.write("      navLinks.classList.toggle(\"show-links\");\r\n");
      out.write("      menu.classList.toggle(\"menu-change\");\r\n");
      out.write("    };\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
